In [2]:
print("Hello World")

Hello World


In [4]:
import numpy as np
p = [[1,0],[0,1]]
q = [[1,2],[3,4]]
print("Original Matrix")
print(p)
print(q)

Original Matrix
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]


In [5]:
result1 = np.dot(p,q)
print(result1)

[[1 2]
 [3 4]]


In [6]:
def multiply_matrices(p,q) :
    return np.dot(p,q)

p = [[1,0],[0,1]]
q = [[1,2],[3,4]]
result2= multiply_matrices(p,q)
print(result2)

[[1 2]
 [3 4]]


In [7]:
a = np.array([[1,0],[1,2]])
print(a)


[[1 0]
 [1 2]]


In [9]:
print("Determinant is: ")
print(np.linalg.det(a))

Determinant is: 
2.0


In [10]:
p[0][1]=5
print(p)

[[1, 5], [0, 1]]


In [11]:
print(a*3)

[[3 0]
 [3 6]]


In [12]:
b = np.eye(4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
a[0]

array([1, 0])

In [15]:
c = np.array([[13,4],[5,6]])
print(a+c)

[[14  4]
 [ 6  8]]


In [16]:
q = np.eye(10)
q[5][5]=5
print(q)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [17]:
q[-1][-1]= 7
print(q)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 7.]]


In [19]:
q[-1][-2] = 99
print(q)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 99.  7.]]
